#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;

namespace PGA.Model.DAL	
{
	public partial class PGALayerStates
	{
		private string _bridge="OBR:S-BRIDGES";
		public virtual string Bridge
		{
			get
			{
				return this._bridge;
			}
			set
			{
				this._bridge = value;
			}
		}
		
		private string _building="OBD:S-BUNKER";
		public virtual string Building
		{
			get
			{
				return this._building;
			}
			set
			{
				this._building = value;
			}
		}
		
		private string _bunker="OST:S-BUNKER";
		public virtual string Bunker
		{
			get
			{
				return this._bunker;
			}
			set
			{
				this._bunker = value;
			}
		}
		
		private string _bushOutline="OBO:BUSHOL";
		public virtual string BushOutline
		{
			get
			{
				return this._bushOutline;
			}
			set
			{
				this._bushOutline = value;
			}
		}
		
		private string _cartPath="OCA:CARTPATH";
		public virtual string CartPath
		{
			get
			{
				return this._cartPath;
			}
			set
			{
				this._cartPath = value;
			}
		}
		
		private string _collar="OCO:S-COLLAR";
		public virtual string Collar
		{
			get
			{
				return this._collar;
			}
			set
			{
				this._collar = value;
			}
		}
		
		private string _dirtOutline="ODO:DIRTOL";
		public virtual string DirtOutline
		{
			get
			{
				return this._dirtOutline;
			}
			set
			{
				this._dirtOutline = value;
			}
		}
		
		private string _fairway="OFW:FAIRWAY";
		public virtual string Fairway
		{
			get
			{
				return this._fairway;
			}
			set
			{
				this._fairway = value;
			}
		}
		
		private string _green="OGR:GREEN";
		public virtual string Green
		{
			get
			{
				return this._green;
			}
			set
			{
				this._green = value;
			}
		}
		
		private string _greenSideBunker="OGS:GRN";
		public virtual string GreenSideBunker
		{
			get
			{
				return this._greenSideBunker;
			}
			set
			{
				this._greenSideBunker = value;
			}
		}
		
		private string _intMedRough="IOR:S-IMRO";
		public virtual string IntMedRough
		{
			get
			{
				return this._intMedRough;
			}
			set
			{
				this._intMedRough = value;
			}
		}
		
		private string _landScaping="OLN:TREE-SYMBOLS";
		public virtual string LandScaping
		{
			get
			{
				return this._landScaping;
			}
			set
			{
				this._landScaping = value;
			}
		}
		
		private string _nativeArea="ONA:S-NATIVE";
		public virtual string NativeArea
		{
			get
			{
				return this._nativeArea;
			}
			set
			{
				this._nativeArea = value;
			}
		}
		
		private string _other="OTH:OTHER";
		public virtual string Other
		{
			get
			{
				return this._other;
			}
			set
			{
				this._other = value;
			}
		}
		
		private string _path="OPT:S-PATH";
		public virtual string Path
		{
			get
			{
				return this._path;
			}
			set
			{
				this._path = value;
			}
		}
		
		private string _rockOutline="ORK:S-ROCKS";
		public virtual string RockOutline
		{
			get
			{
				return this._rockOutline;
			}
			set
			{
				this._rockOutline = value;
			}
		}
		
		private string _roughOutline="ORO:ROUGH_OUTLINES";
		public virtual string RoughOutline
		{
			get
			{
				return this._roughOutline;
			}
			set
			{
				this._roughOutline = value;
			}
		}
		
		private string _steps="OSS:S-STEPS";
		public virtual string Steps
		{
			get
			{
				return this._steps;
			}
			set
			{
				this._steps = value;
			}
		}
		
		private string _teeBox="OTB:S-TEEBOX";
		public virtual string TeeBox
		{
			get
			{
				return this._teeBox;
			}
			set
			{
				this._teeBox = value;
			}
		}
		
		private string _treeOutline="OTO:TREEOL";
		public virtual string TreeOutline
		{
			get
			{
				return this._treeOutline;
			}
			set
			{
				this._treeOutline = value;
			}
		}
		
		private string _walkStrip="OWS:WST";
		public virtual string WalkStrip
		{
			get
			{
				return this._walkStrip;
			}
			set
			{
				this._walkStrip = value;
			}
		}
		
		private string _wall="OWL:WALL";
		public virtual string Wall
		{
			get
			{
				return this._wall;
			}
			set
			{
				this._wall = value;
			}
		}
		
		private string _water="OWA:WATER";
		public virtual string Water
		{
			get
			{
				return this._water;
			}
			set
			{
				this._water = value;
			}
		}
		
		private string _waterDrop="OWD:S-WATER";
		public virtual string WaterDrop
		{
			get
			{
				return this._waterDrop;
			}
			set
			{
				this._waterDrop = value;
			}
		}
		
		private uint _layerStateID;
		public virtual uint LayerStateID
		{
			get
			{
				return this._layerStateID;
			}
			set
			{
				this._layerStateID = value;
			}
		}
		
	}
}
#pragma warning restore 1591
