#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#region

using System.IO;

#endregion

namespace PGA.Model.BLL
{
    public class PGAFeatureObjects
    {
        public virtual int Id { get; set; }

        public virtual Stream Feature { get; set; }

        public virtual string Name { get; set; }

        public virtual string Type { get; set; }

        public virtual string Layer { get; set; }
    }
}

#pragma warning restore 1591