
#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGA.Model.BLL
{
    public class LayerStatesBLL
    {
        public virtual string Bridge { get; set; } = "OBR:S-BRIDGES";

        public virtual string Building { get; set; } = "OBD:S-BUILDING";

        public virtual string Bunker { get; set; } = "OST:S-BUNKER";

        public virtual string BushOutline { get; set; } = "OBO:S-BUSH";

        public virtual string CartPath { get; set; } = "OCA:S-CARTPATH";

        public virtual string Collar { get; set; } = "OCO:S-COLLAR";

        public virtual string DirtOutline { get; set; } = "ODO:S-DIRT-OUTLINE";

        public virtual string Fairway { get; set; } = "OFW:S-FAIRWAY";

        public virtual string Green { get; set; } = "OGR:S-GREEN";

        public virtual string GreenSideBunker { get; set; } = "OGS:S-GREENSIDE-BUNKER";

        public virtual string IntMedRough { get; set; } = "IOR:S-INTERMEDIATE-ROUGH";

        public virtual string LandScaping { get; set; } = "OLN:S-LANDSCAPING";

        public virtual string NativeArea { get; set; } = "ONA:S-NATIVE-AREA";

        public virtual string Other { get; set; } = "OTH:S-OTHER";

        public virtual string Path { get; set; } = "OPT:S-PATH";

        public virtual string RockOutline { get; set; } = "ORK:S-ROCK-OUTLINE";

        public virtual string RoughOutline { get; set; } = "ORO:S-ROUGH-OUTLINES";

        public virtual string Steps { get; set; } = "OSS:S-STEPS";

        public virtual string TeeBox { get; set; } = "OTB:S-TEE-BOX";

        public virtual string TreeOutline { get; set; } = "OTO:S-TREE-OUTLINE";

        public virtual string WalkStrip { get; set; } = "OWS:S-WALK-STRIP";

        public virtual string Wall { get; set; } = "OWL:S-WALL";

        public virtual string Water { get; set; } = "OWA:S-WATER";

        public virtual string WaterDrop { get; set; } = "OWD:S-WATER-DROP";

        public virtual uint LayerStateID { get; set; }
    }
}

#pragma warning restore 1591